### PR TITLE
Create contact form

### PR DESCRIPTION
**Pull request by mrEckendonk**
## Hello Code Reviewer

In this task, we created in PP a contact form. The form works and sends an email when the user hits the "Get in Touch" button.

We used formspree.io to send the email

PS; sorry for the "resolve conflicts", but something went wrong somewhere, but I don't have a clue where.
Deleting and recreating files resolved it

### CODE REVIEW

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
### Hi @Eckybrazzz, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by alonsofalconi — COMMENTED** [review]
Hi @Eckybrazzz,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is already approved and merged. I would suggest opening a new PR for this specific milestone (application deployment).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by alonsofalconi — COMMENTED** [review]
Hi @Eckybrazzz,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is already approved and merged. I would suggest opening a new PR for this specific milestone (application deployment).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mrEckendonk** [comment]
I'm sorry, but the instructions were not very clear about it. You can find them below. I made a new PR for this and only change a word in the READMW.md.  In my opinion, Microverse should change the text inside the page so it's clear that if you already had the link inside your README.md you should create always a new PR

image

The only issue here is that the requested links did not work, so I used the link for my project. (when submitting them for a review)

**Comment by alonsofalconi** [comment]
Hello, @Eckybrazzz!
I hope you're doing well. I understand, but the thing is that this branch it's already merged and this PR it's not for the actual activity/milestone. Please, take into consideration that each project requires a new and not-merged PR. Remember that in Microverse we prepare for a future working environment where we MUST stick to good practices. Following a proper workflow since the beginning will be helpful in the future :wink: :raised_hands:

**Pull request merged**
